import type {
    AnswerReleaseDecision,
    AnswerReleaseGateId,
    KnowledgeQueryResolvedScope,
    RagContextBudget,
    RagEvidenceRole,
    RagFailureStage,
    RagSourceDecision,
    RagSourceBoundary,
    RagSufficiencyReview,
    RelationKind,
} from './types';

export interface KnowledgeWorkspaceConversationRegressionExpectation {
    minCitations: number;
    scopeSource: NonNullable<KnowledgeQueryResolvedScope['scopeSource']>;
    answerReleaseDecision?: AnswerReleaseDecision;
    acceptedAnswerReleaseDecisions?: AnswerReleaseDecision[];
    runtimeAnswerReleaseDecision?: AnswerReleaseDecision;
    runtimeRequiredFailedGateIds?: AnswerReleaseGateId[];
    plannerTitleLikeQueries: string[];
    retrievalModes?: string[];
    primarySourcePath: string;
    recoveredSourcePaths?: string[];
    answerMustContain?: string[];
    answerMustNotContain?: string[];
    ragSourceBoundary?: RagSourceBoundary;
    requiredRagRoles?: RagEvidenceRole[];
    forbiddenRagRoles?: RagEvidenceRole[];
    minimumRagFullDocumentFragmentCounts?: Partial<Record<RagEvidenceRole, number>>;
    acceptedRagSufficiencyStatuses?: Array<RagSufficiencyReview['status']>;
    expectedRagBudget?: Partial<RagContextBudget>;
    minimumRagSourceDecisionStatusCounts?: Partial<Record<RagSourceDecision['status'], number>>;
    inMemoryMinimumRagSourceDecisionStatusCounts?: Partial<Record<RagSourceDecision['status'], number>>;
    requiredRagFailureStages?: RagFailureStage[];
    runtimeRequiredRagFailureStages?: RagFailureStage[];
    runtimeAcceptedRagSufficiencyStatuses?: Array<RagSufficiencyReview['status']>;
    runtimeAcceptedRagDegradationStates?: Array<NonNullable<RagSufficiencyReview['degradationState']>>;
    runtimeRequiredRagSufficiencyReasonFragments?: string[];
    runtimeRequiredRagSourceDecisionReasonFragments?: string[];
    expectedRagDeterministic?: boolean;
    expectedRagLlmJudgeUsed?: boolean;
    expectedRagRecoveryAttempted?: boolean;
    inMemoryExpectedRagRecoveryAttempted?: boolean;
    acceptedRagDegradationStates?: Array<NonNullable<RagSufficiencyReview['degradationState']>>;
    minimumRagRecoveryBeforeSourceDecisionStatusCounts?: Partial<Record<RagSourceDecision['status'], number>>;
    inMemoryMinimumRagRecoveryBeforeSourceDecisionStatusCounts?: Partial<Record<RagSourceDecision['status'], number>>;
    requiredRagRecoveryBeforeReasonFragments?: string[];
    runtimeRequiredRagRecoveryBeforeReasonFragments?: string[];
    requiredFirstGraphSuccessorTitle?: string;
    requiredGraphSuccessorTitles?: string[];
    forbiddenGraphSuccessorTitles?: string[];
    requiredGraphSuccessorRelationKinds?: RelationKind[];
    forbiddenGraphNeighborFragmentTitles?: string[];
    minimumGraphIntentAlignedPredecessorCandidates?: number;
    minimumGraphIntentAlignedSuccessorCandidates?: number;
    minimumGraphIntentMisalignedPredecessorCandidates?: number;
    minimumGraphIntentMisalignedSuccessorCandidates?: number;
    expectedGraphUsedMisalignedPredecessorFallback?: boolean;
    expectedGraphUsedMisalignedSuccessorFallback?: boolean;
    requirePlannerTitleHitDocumentIds?: boolean;
    requireScopedDocumentIds?: boolean;
}

export interface KnowledgeWorkspaceConversationRegressionCase {
    id: string;
    description: string;
    preloadTargets: string[];
    activeTarget: string;
    query: string;
    topK?: number;
    runtimeProviderFixture?: 'malformed_json' | 'timeout';
    runtimeUnavailableSourcePaths?: string[];
    expected: KnowledgeWorkspaceConversationRegressionExpectation;
}

function freezeRegressionCases(
    cases: KnowledgeWorkspaceConversationRegressionCase[]
): KnowledgeWorkspaceConversationRegressionCase[] {
    const seenIds = new Set<string>();
    cases.forEach((entry) => {
        const id = String(entry.id || '').trim();
        if (!id) {
            throw new Error('Knowledge workspace conversation regression cases require a non-empty id.');
        }
        if (seenIds.has(id)) {
            throw new Error(`Duplicate knowledge workspace conversation regression case id: ${id}`);
        }
        seenIds.add(id);
        if (!Array.isArray(entry.preloadTargets) || entry.preloadTargets.length <= 0) {
            throw new Error(`Knowledge workspace conversation regression case "${id}" requires preload targets.`);
        }
        const normalizedActiveTarget = String(entry.activeTarget || '').trim();
        if (!normalizedActiveTarget) {
            throw new Error(`Knowledge workspace conversation regression case "${id}" requires an activeTarget.`);
        }
        if (!entry.preloadTargets.some((target) => String(target || '').trim() === normalizedActiveTarget)) {
            throw new Error(
                `Knowledge workspace conversation regression case "${id}" must include the activeTarget in preloadTargets.`
            );
        }
    });
    return cases;
}

export const KNOWLEDGE_WORKSPACE_CONVERSATION_REGRESSION_CASES = freezeRegressionCases([
    {
        id: 'waterglass_explicit_scope_compact_zh',
        description: 'Compact mixed-language alias inside the explicit waterglass scope should retrieve grounded evidence.',
        preloadTargets: ['waterglass'],
        activeTarget: 'waterglass',
        query: '什么是waterglass?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            runtimeAnswerReleaseDecision: 'revise',
            runtimeRequiredFailedGateIds: ['query_intent_alignment', 'rag_claim_citation_support'],
            plannerTitleLikeQueries: ['waterglass', 'water glass'],
            primarySourcePath: 'Knowledge_Base/waterglass/water glass.md',
            answerMustContain: ['水杯', '透明', '容器'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                '本技术文档旨在',
                '所有推理过程',
                '最终输出',
                '遵从您的指示',
                '遵从您的要求',
                'all reasoning',
                'final output',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context', 'graph_neighbor_support'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
        },
    },
    {
        id: 'waterglass_explicit_scope_spaced_zh',
        description: 'Spaced mixed-language alias inside the explicit waterglass scope should retrieve the same grounded note.',
        preloadTargets: ['waterglass'],
        activeTarget: 'waterglass',
        query: '什么是water glass',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            runtimeAnswerReleaseDecision: 'revise',
            runtimeRequiredFailedGateIds: ['query_intent_alignment', 'rag_claim_citation_support'],
            plannerTitleLikeQueries: ['water glass', 'waterglass'],
            primarySourcePath: 'Knowledge_Base/waterglass/water glass.md',
            answerMustContain: ['水杯', '透明', '容器'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                '本技术文档旨在',
                '所有推理过程',
                '最终输出',
                '遵从您的指示',
                '遵从您的要求',
                'all reasoning',
                'final output',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context', 'graph_neighbor_support'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
        },
    },
    {
        id: 'waterglass_compare_materials_en',
        description: 'Compare-intent query in the explicit waterglass scope should keep evidence for both container materials.',
        preloadTargets: ['waterglass'],
        activeTarget: 'waterglass',
        query: 'compare water glass and plastic cup',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['water glass', 'plastic cup'],
            primarySourcePath: 'Knowledge_Base/waterglass/water glass.md',
            answerMustContain: ['glass', 'plastic'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context', 'graph_neighbor_support'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'graphintent_compare_neighbor_selection_en',
        description: 'Compare-intent graph assembly should prefer material analogy neighbors over a higher-confidence procedural sequence edge.',
        preloadTargets: ['graphintent'],
        activeTarget: 'graphintent',
        query: 'compare brittle glass vessel with polymer cup material behavior',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['brittle glass vessel', 'polymer cup material behavior'],
            primarySourcePath: 'Knowledge_Base/graphintent/brittle glass vessel.md',
            answerMustContain: ['Brittle', 'Ductile', 'Polymer'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'Procedural Calibration Sequence',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context', 'graph_neighbor_support'],
            minimumRagFullDocumentFragmentCounts: {
                graph_neighbor_support: 1,
            },
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            requiredGraphSuccessorTitles: [
                'Ductile Polymer Cup Analogy',
                'Reusable Polymer Vessel Analogy',
            ],
            forbiddenGraphSuccessorTitles: ['Procedural Calibration Sequence'],
            requiredGraphSuccessorRelationKinds: ['analogy'],
            forbiddenGraphNeighborFragmentTitles: ['Procedural Calibration Sequence'],
            minimumGraphIntentAlignedSuccessorCandidates: 2,
            minimumGraphIntentMisalignedSuccessorCandidates: 1,
            expectedGraphUsedMisalignedSuccessorFallback: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'graphintent_missing_neighbor_source_window_en',
        description: 'Graph-neighbor source-window loss should degrade graph evidence instead of treating direct spans as complete graph support.',
        preloadTargets: ['graphintent'],
        activeTarget: 'graphintent',
        query: 'compare brittle glass vessel with polymer cup material behavior',
        runtimeUnavailableSourcePaths: [
            'Knowledge_Base/graphintent/ductile polymer cup analogy.md',
            'Knowledge_Base/graphintent/reusable polymer vessel analogy.md',
        ],
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['brittle glass vessel', 'polymer cup material behavior'],
            primarySourcePath: 'Knowledge_Base/graphintent/brittle glass vessel.md',
            answerMustContain: ['Brittle'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context', 'graph_neighbor_support'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            runtimeAcceptedRagSufficiencyStatuses: ['borderline'],
            acceptedRagDegradationStates: ['none', 'partial_coverage'],
            runtimeAcceptedRagDegradationStates: ['partial_coverage'],
            minimumRagSourceDecisionStatusCounts: {
                source_window_unavailable: 1,
            },
            inMemoryMinimumRagSourceDecisionStatusCounts: {
                read: 1,
            },
            runtimeRequiredRagFailureStages: ['parsing_source', 'graph_evidence'],
            runtimeRequiredRagSufficiencyReasonFragments: ['graph_neighbor_evidence_missing'],
            runtimeRequiredRagSourceDecisionReasonFragments: ['graph_neighbor_support'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            expectedRagRecoveryAttempted: true,
            inMemoryExpectedRagRecoveryAttempted: false,
            requiredGraphSuccessorTitles: [
                'Ductile Polymer Cup Analogy',
                'Reusable Polymer Vessel Analogy',
            ],
            requiredGraphSuccessorRelationKinds: ['analogy'],
            minimumGraphIntentAlignedSuccessorCandidates: 2,
            minimumGraphIntentMisalignedSuccessorCandidates: 1,
            expectedGraphUsedMisalignedSuccessorFallback: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'graphintent_multi_neighbor_source_loss_en',
        description: 'Multiple graph-neighbor source-window losses should be recorded per neighbor document and degrade graph evidence as partial coverage.',
        preloadTargets: ['graphintent'],
        activeTarget: 'graphintent',
        query: 'compare brittle glass vessel with polymer cup material behavior',
        runtimeUnavailableSourcePaths: [
            'Knowledge_Base/graphintent/ductile polymer cup analogy.md',
            'Knowledge_Base/graphintent/reusable polymer vessel analogy.md',
        ],
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['brittle glass vessel', 'polymer cup material behavior'],
            primarySourcePath: 'Knowledge_Base/graphintent/brittle glass vessel.md',
            answerMustContain: ['Brittle'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context', 'graph_neighbor_support'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            runtimeAcceptedRagSufficiencyStatuses: ['borderline'],
            acceptedRagDegradationStates: ['none', 'partial_coverage'],
            runtimeAcceptedRagDegradationStates: ['partial_coverage'],
            minimumRagSourceDecisionStatusCounts: {
                source_window_unavailable: 2,
            },
            inMemoryMinimumRagSourceDecisionStatusCounts: {
                read: 1,
            },
            runtimeRequiredRagFailureStages: ['parsing_source', 'graph_evidence'],
            runtimeRequiredRagSufficiencyReasonFragments: ['graph_neighbor_evidence_missing'],
            runtimeRequiredRagSourceDecisionReasonFragments: ['graph_neighbor_support'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            expectedRagRecoveryAttempted: true,
            inMemoryExpectedRagRecoveryAttempted: false,
            requiredGraphSuccessorTitles: [
                'Ductile Polymer Cup Analogy',
                'Reusable Polymer Vessel Analogy',
            ],
            requiredGraphSuccessorRelationKinds: ['analogy'],
            minimumGraphIntentAlignedSuccessorCandidates: 2,
            minimumGraphIntentMisalignedSuccessorCandidates: 1,
            expectedGraphUsedMisalignedSuccessorFallback: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'financial_scope_recovery_spaced_en',
        description: 'A spaced title-like query should recover from the financial scope into the waterglass note when the selected scope misses.',
        preloadTargets: ['financial', 'waterglass'],
        activeTarget: 'financial',
        query: 'what is water glass?',
        expected: {
            minCitations: 1,
            scopeSource: 'planner_scope_recovery',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['water glass', 'waterglass'],
            retrievalModes: ['planner_scope_recovery'],
            primarySourcePath: 'Knowledge_Base/waterglass/water glass.md',
            recoveredSourcePaths: ['Knowledge_Base/waterglass/water glass.md'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
            ],
        },
    },
    {
        id: 'financial_scope_recovery_compact_en',
        description: 'A compact alias should also recover from the financial scope into the waterglass note without leaking diagnostics.',
        preloadTargets: ['financial', 'waterglass'],
        activeTarget: 'financial',
        query: 'what is waterglass?',
        expected: {
            minCitations: 1,
            scopeSource: 'planner_scope_recovery',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['waterglass', 'water glass'],
            retrievalModes: ['planner_scope_recovery'],
            primarySourcePath: 'Knowledge_Base/waterglass/water glass.md',
            recoveredSourcePaths: ['Knowledge_Base/waterglass/water glass.md'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
            ],
        },
    },
    {
        id: 'conflicting_adjacent_evidence_probe_en',
        description: 'A scoped note with adjacent contradictory tolerance values should degrade as conflict instead of publishing one stable value.',
        preloadTargets: ['ragconflict'],
        activeTarget: 'ragconflict',
        query: 'what is calibration tolerance conflict probe?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['calibration tolerance conflict probe'],
            primarySourcePath: 'Knowledge_Base/ragconflict/calibration tolerance conflict probe.md',
            answerMustContain: ['calibration tolerance', '+/-0.10 mm', '+/-0.50 mm'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'single stable calibration tolerance',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context', 'conflict'],
            acceptedRagSufficiencyStatuses: ['borderline'],
            acceptedRagDegradationStates: ['conflict'],
            requiredRagFailureStages: ['context_assembly'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'conflicting_nonadjacent_section_evidence_probe_en',
        description: 'A scoped note with non-adjacent contradictory tolerance values in one section should still degrade as conflict.',
        preloadTargets: ['ragconflict'],
        activeTarget: 'ragconflict',
        query: 'what is remote calibration tolerance conflict probe?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['remote calibration tolerance conflict probe'],
            primarySourcePath: 'Knowledge_Base/ragconflict/remote calibration tolerance conflict probe.md',
            answerMustContain: ['calibration tolerance', '+/-0.10 mm', '+/-0.50 mm'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'single stable calibration tolerance',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context', 'conflict'],
            acceptedRagSufficiencyStatuses: ['borderline'],
            acceptedRagDegradationStates: ['conflict'],
            requiredRagFailureStages: ['context_assembly'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'conflicting_release_date_evidence_probe_en',
        description: 'A scoped note with contradictory release dates in one section should degrade as conflict instead of publishing one stable date.',
        preloadTargets: ['ragdateconflict'],
        activeTarget: 'ragdateconflict',
        query: 'what is release date conflict probe?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['release date conflict probe'],
            primarySourcePath: 'Knowledge_Base/ragdateconflict/release date conflict probe.md',
            answerMustContain: ['migration release date', '2026-07-01', '2026-08-15'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'stable migration release date',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context', 'conflict'],
            acceptedRagSufficiencyStatuses: ['borderline'],
            acceptedRagDegradationStates: ['conflict'],
            requiredRagFailureStages: ['context_assembly'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'conflicting_state_status_evidence_probe_en',
        description: 'A scoped note with contradictory categorical status facts should degrade as conflict instead of publishing one stable status.',
        preloadTargets: ['ragstateconflict'],
        activeTarget: 'ragstateconflict',
        query: 'what is state status conflict probe?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['state status conflict probe'],
            primarySourcePath: 'Knowledge_Base/ragstateconflict/state status conflict probe.md',
            answerMustContain: ['migration gate status', 'enabled', 'disabled'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'stable migration gate status',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context', 'conflict'],
            acceptedRagSufficiencyStatuses: ['borderline'],
            acceptedRagDegradationStates: ['conflict'],
            requiredRagFailureStages: ['context_assembly'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'conflicting_quantity_limit_evidence_probe_en',
        description: 'A scoped note with contradictory unitless operational limits should degrade as conflict instead of publishing one stable limit.',
        preloadTargets: ['ragquantityconflict'],
        activeTarget: 'ragquantityconflict',
        query: 'what is quantity limit conflict probe?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['quantity limit conflict probe'],
            primarySourcePath: 'Knowledge_Base/ragquantityconflict/quantity limit conflict probe.md',
            answerMustContain: ['retry limit', '3', '5'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'stable retry limit',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context', 'conflict'],
            acceptedRagSufficiencyStatuses: ['borderline'],
            acceptedRagDegradationStates: ['conflict'],
            requiredRagFailureStages: ['context_assembly'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'conflicting_ownership_identity_evidence_probe_en',
        description: 'A scoped note with contradictory ownership identity facts should degrade as conflict instead of publishing one stable owner.',
        preloadTargets: ['ragidentityconflict'],
        activeTarget: 'ragidentityconflict',
        query: 'what is ownership conflict probe?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['ownership conflict probe'],
            primarySourcePath: 'Knowledge_Base/ragidentityconflict/ownership conflict probe.md',
            answerMustContain: ['deployment owner', 'Release Ops', 'Rollback Team'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'stable deployment owner',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context', 'conflict'],
            acceptedRagSufficiencyStatuses: ['borderline'],
            acceptedRagDegradationStates: ['conflict'],
            requiredRagFailureStages: ['context_assembly'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'conflicting_multi_document_ownership_identity_evidence_probe_en',
        description: 'Two scoped documents with contradictory ownership identity facts should degrade as cross-document conflict.',
        preloadTargets: ['ragidentitymulticonflict'],
        activeTarget: 'ragidentitymulticonflict',
        query: 'compare handoff deployment owner conflict probe with rollback deployment owner conflict evidence',
        expected: {
            minCitations: 2,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: [
                'handoff deployment owner conflict probe',
                'rollback deployment owner conflict evidence',
            ],
            primarySourcePath: 'Knowledge_Base/ragidentitymulticonflict/handoff deployment owner conflict probe.md',
            answerMustContain: ['deployment owner', 'Release Ops', 'Rollback Team'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'stable deployment owner',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context', 'conflict'],
            acceptedRagSufficiencyStatuses: ['borderline'],
            acceptedRagDegradationStates: ['conflict'],
            requiredRagFailureStages: ['context_assembly'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'conflicting_endpoint_evidence_probe_en',
        description: 'A scoped note with contradictory controlled endpoint facts should degrade as conflict instead of publishing one stable route.',
        preloadTargets: ['ragendpointconflict'],
        activeTarget: 'ragendpointconflict',
        query: 'what is endpoint conflict probe?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['endpoint conflict probe'],
            primarySourcePath: 'Knowledge_Base/ragendpointconflict/endpoint conflict probe.md',
            answerMustContain: ['webhook endpoint', '/api/v1/hooks', '/api/v2/hooks'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'stable webhook endpoint',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context', 'conflict'],
            acceptedRagSufficiencyStatuses: ['borderline'],
            acceptedRagDegradationStates: ['conflict'],
            requiredRagFailureStages: ['context_assembly'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'full_document_endpoint_scan_remote_conflict_probe_en',
        description: 'Two scoped endpoint documents should be fully scanned for remote webhook route contradictions outside the matched opening spans.',
        preloadTargets: ['ragendpointfullscan'],
        activeTarget: 'ragendpointfullscan',
        query: 'compare nominal endpoint full scan source with field endpoint full scan source',
        expected: {
            minCitations: 2,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: [
                'nominal endpoint full scan source',
                'field endpoint full scan source',
            ],
            primarySourcePath: 'Knowledge_Base/ragendpointfullscan/nominal endpoint full scan source.md',
            answerMustContain: ['webhook endpoint', '/api/v1/hooks', '/api/v2/hooks'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'stable webhook endpoint',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context', 'conflict'],
            acceptedRagSufficiencyStatuses: ['borderline'],
            acceptedRagDegradationStates: ['conflict'],
            requiredRagFailureStages: ['context_assembly'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'environment_scoped_endpoint_probe_en',
        description: 'A scoped note with staging and production endpoint facts should retain both environment-qualified routes without degrading as a conflict.',
        preloadTargets: ['ragendpointqualifier'],
        activeTarget: 'ragendpointqualifier',
        query: 'what is environment scoped endpoint probe?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['environment scoped endpoint probe'],
            primarySourcePath: 'Knowledge_Base/ragendpointqualifier/environment scoped endpoint probe.md',
            answerMustContain: ['webhook endpoint', '/api/staging/hooks', 'staging'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'Conflicting evidence',
                'stable webhook endpoint',
                'immediate predecessors',
                'likely next nodes',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context'],
            forbiddenRagRoles: ['conflict'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            acceptedRagDegradationStates: ['none'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'conflicting_dependency_evidence_probe_en',
        description: 'A scoped note with contradictory controlled dependency facts should degrade as conflict instead of publishing one stable dependency.',
        preloadTargets: ['ragdependencyconflict'],
        activeTarget: 'ragdependencyconflict',
        query: 'what is dependency conflict probe?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['dependency conflict probe'],
            primarySourcePath: 'Knowledge_Base/ragdependencyconflict/dependency conflict probe.md',
            answerMustContain: ['storage dependency', 'SQLite', 'PostgreSQL'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'stable storage dependency',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context', 'conflict'],
            acceptedRagSufficiencyStatuses: ['borderline'],
            acceptedRagDegradationStates: ['conflict'],
            requiredRagFailureStages: ['context_assembly'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'environment_scoped_dependency_probe_en',
        description: 'A scoped note with staging and production dependency facts should retain both environment-qualified dependencies without degrading as a conflict.',
        preloadTargets: ['ragdependencyqualifier'],
        activeTarget: 'ragdependencyqualifier',
        query: 'what is environment scoped dependency probe?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['environment scoped dependency probe'],
            primarySourcePath: 'Knowledge_Base/ragdependencyqualifier/environment scoped dependency probe.md',
            answerMustContain: ['storage dependency', 'SQLite', 'staging'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'Conflicting evidence',
                'stable storage dependency',
                'immediate predecessors',
                'likely next nodes',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context'],
            forbiddenRagRoles: ['conflict'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            acceptedRagDegradationStates: ['none'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'conflicting_multi_document_dependency_evidence_probe_en',
        description: 'Two scoped documents with contradictory controlled dependency facts should degrade as cross-document conflict.',
        preloadTargets: ['ragdependencymulticonflict'],
        activeTarget: 'ragdependencymulticonflict',
        query: 'compare nominal storage dependency conflict probe with field storage dependency conflict evidence',
        expected: {
            minCitations: 2,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: [
                'nominal storage dependency conflict probe',
                'field storage dependency conflict evidence',
            ],
            primarySourcePath: 'Knowledge_Base/ragdependencymulticonflict/nominal storage dependency conflict probe.md',
            answerMustContain: ['storage dependency', 'SQLite', 'PostgreSQL'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'stable storage dependency',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context', 'conflict'],
            acceptedRagSufficiencyStatuses: ['borderline'],
            acceptedRagDegradationStates: ['conflict'],
            requiredRagFailureStages: ['context_assembly'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'full_document_dependency_scan_remote_conflict_probe_en',
        description: 'Two scoped dependency documents should be fully scanned for remote dependency contradictions outside the matched opening spans.',
        preloadTargets: ['ragdependencyfullscan'],
        activeTarget: 'ragdependencyfullscan',
        query: 'compare nominal dependency full scan source with field dependency full scan source',
        expected: {
            minCitations: 2,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: [
                'nominal dependency full scan source',
                'field dependency full scan source',
            ],
            primarySourcePath: 'Knowledge_Base/ragdependencyfullscan/nominal dependency full scan source.md',
            answerMustContain: ['storage dependency', 'SQLite', 'PostgreSQL'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'stable storage dependency',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context', 'conflict'],
            acceptedRagSufficiencyStatuses: ['borderline'],
            acceptedRagDegradationStates: ['conflict'],
            requiredRagFailureStages: ['context_assembly'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'full_document_format_scan_remote_conflict_probe_en',
        description: 'Two scoped format documents should be fully scanned for remote payload format contradictions outside the matched opening spans.',
        preloadTargets: ['ragformatfullscan'],
        activeTarget: 'ragformatfullscan',
        query: 'compare nominal format full scan source with field format full scan source',
        expected: {
            minCitations: 2,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: [
                'nominal format full scan source',
                'field format full scan source',
            ],
            primarySourcePath: 'Knowledge_Base/ragformatfullscan/nominal format full scan source.md',
            answerMustContain: ['payload format', 'JSON', 'YAML'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'stable payload format',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context', 'conflict'],
            acceptedRagSufficiencyStatuses: ['borderline'],
            acceptedRagDegradationStates: ['conflict'],
            requiredRagFailureStages: ['context_assembly'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'full_document_protocol_scan_remote_conflict_probe_en',
        description: 'Two scoped protocol documents should be fully scanned for remote transport protocol contradictions outside the matched opening spans.',
        preloadTargets: ['ragprotocolfullscan'],
        activeTarget: 'ragprotocolfullscan',
        query: 'compare nominal protocol full scan source with field protocol full scan source',
        expected: {
            minCitations: 2,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: [
                'nominal protocol full scan source',
                'field protocol full scan source',
            ],
            primarySourcePath: 'Knowledge_Base/ragprotocolfullscan/nominal protocol full scan source.md',
            answerMustContain: ['transport protocol', 'HTTP/1.1', 'WebSocket'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'stable transport protocol',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context', 'conflict'],
            acceptedRagSufficiencyStatuses: ['borderline'],
            acceptedRagDegradationStates: ['conflict'],
            requiredRagFailureStages: ['context_assembly'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'conflicting_format_evidence_probe_en',
        description: 'A scoped note with contradictory controlled format facts should degrade as conflict instead of publishing one stable payload format.',
        preloadTargets: ['ragformatconflict'],
        activeTarget: 'ragformatconflict',
        query: 'what is format conflict probe?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['format conflict probe'],
            primarySourcePath: 'Knowledge_Base/ragformatconflict/format conflict probe.md',
            answerMustContain: ['payload format', 'JSON', 'YAML'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'stable payload format',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context', 'conflict'],
            acceptedRagSufficiencyStatuses: ['borderline'],
            acceptedRagDegradationStates: ['conflict'],
            requiredRagFailureStages: ['context_assembly'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'environment_scoped_format_probe_en',
        description: 'A scoped note with staging and production format facts should retain both environment-qualified formats without degrading as a conflict.',
        preloadTargets: ['ragformatqualifier'],
        activeTarget: 'ragformatqualifier',
        query: 'what is environment scoped format probe?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['environment scoped format probe'],
            primarySourcePath: 'Knowledge_Base/ragformatqualifier/environment scoped format probe.md',
            answerMustContain: ['payload format', 'JSON', 'staging'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'Conflicting evidence',
                'stable payload format',
                'immediate predecessors',
                'likely next nodes',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context'],
            forbiddenRagRoles: ['conflict'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            acceptedRagDegradationStates: ['none'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'conflicting_protocol_evidence_probe_en',
        description: 'A scoped note with contradictory controlled protocol facts should degrade as conflict instead of publishing one stable transport protocol.',
        preloadTargets: ['ragprotocolconflict'],
        activeTarget: 'ragprotocolconflict',
        query: 'what is protocol conflict probe?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['protocol conflict probe'],
            primarySourcePath: 'Knowledge_Base/ragprotocolconflict/protocol conflict probe.md',
            answerMustContain: ['transport protocol', 'HTTP/1.1', 'WebSocket'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'stable transport protocol',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context', 'conflict'],
            acceptedRagSufficiencyStatuses: ['borderline'],
            acceptedRagDegradationStates: ['conflict'],
            requiredRagFailureStages: ['context_assembly'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'environment_scoped_protocol_probe_en',
        description: 'A scoped note with staging and production protocol facts should retain both environment-qualified protocols without degrading as a conflict.',
        preloadTargets: ['ragprotocolqualifier'],
        activeTarget: 'ragprotocolqualifier',
        query: 'what is environment scoped protocol probe?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['environment scoped protocol probe'],
            primarySourcePath: 'Knowledge_Base/ragprotocolqualifier/environment scoped protocol probe.md',
            answerMustContain: ['transport protocol', 'HTTP/2', 'staging'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'Conflicting evidence',
                'stable transport protocol',
                'immediate predecessors',
                'likely next nodes',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context'],
            forbiddenRagRoles: ['conflict'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            acceptedRagDegradationStates: ['none'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'version_scoped_dependency_probe_en',
        description: 'A scoped note with version-specific dependency facts should retain both dependencies without degrading as a conflict.',
        preloadTargets: ['ragdependencyversionqualifier'],
        activeTarget: 'ragdependencyversionqualifier',
        query: 'what is version scoped dependency probe?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['version scoped dependency probe'],
            primarySourcePath: 'Knowledge_Base/ragdependencyversionqualifier/version scoped dependency probe.md',
            answerMustContain: ['storage dependency', 'SQLite', 'version 1.0'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'Conflicting evidence',
                'stable storage dependency',
                'immediate predecessors',
                'likely next nodes',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context'],
            forbiddenRagRoles: ['conflict'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            acceptedRagDegradationStates: ['none'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'cross_document_environment_scoped_ownership_identity_probe_en',
        description: 'Two scoped documents with environment-specific owner facts should retain both facts without degrading as a cross-document conflict.',
        preloadTargets: ['ragconditionownercrossscope'],
        activeTarget: 'ragconditionownercrossscope',
        query: 'compare cross environment staging owner source with cross environment production owner source',
        expected: {
            minCitations: 2,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: [
                'cross environment staging owner source',
                'cross environment production owner source',
            ],
            primarySourcePath: 'Knowledge_Base/ragconditionownercrossscope/cross environment staging owner source.md',
            answerMustContain: ['deployment owner', 'Release Ops', 'Rollback Team', 'staging', 'production'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'Conflicting evidence',
                'stable deployment owner',
                'immediate predecessors',
                'likely next nodes',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context'],
            forbiddenRagRoles: ['conflict'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            acceptedRagDegradationStates: ['none'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'cross_document_version_scoped_ownership_identity_probe_en',
        description: 'Two scoped documents with version-specific owner facts should retain both facts without degrading as a cross-document conflict.',
        preloadTargets: ['ragconditionownercrossscope'],
        activeTarget: 'ragconditionownercrossscope',
        query: 'compare cross version one owner source with cross version two owner source',
        expected: {
            minCitations: 2,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: [
                'cross version one owner source',
                'cross version two owner source',
            ],
            primarySourcePath: 'Knowledge_Base/ragconditionownercrossscope/cross version one owner source.md',
            answerMustContain: ['deployment owner', 'Release Ops', 'Rollback Team', 'version 1.0', 'version 2.0'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'Conflicting evidence',
                'stable deployment owner',
                'immediate predecessors',
                'likely next nodes',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context'],
            forbiddenRagRoles: ['conflict'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            acceptedRagDegradationStates: ['none'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'cross_document_platform_scoped_ownership_identity_probe_en',
        description: 'Two scoped documents with platform-specific owner facts should retain both facts without degrading as a cross-document conflict.',
        preloadTargets: ['ragconditionownercrossscope'],
        activeTarget: 'ragconditionownercrossscope',
        query: 'compare cross platform windows owner source with cross platform android owner source',
        expected: {
            minCitations: 2,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: [
                'cross platform windows owner source',
                'cross platform android owner source',
            ],
            primarySourcePath: 'Knowledge_Base/ragconditionownercrossscope/cross platform windows owner source.md',
            answerMustContain: ['deployment owner', 'Release Ops', 'Rollback Team', 'Windows', 'Android'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'Conflicting evidence',
                'stable deployment owner',
                'immediate predecessors',
                'likely next nodes',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context'],
            forbiddenRagRoles: ['conflict'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            acceptedRagDegradationStates: ['none'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'conflicting_location_evidence_probe_en',
        description: 'A scoped note with contradictory controlled location facts should degrade as conflict instead of publishing one stable location.',
        preloadTargets: ['raglocationconflict'],
        activeTarget: 'raglocationconflict',
        query: 'what is location conflict probe?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['location conflict probe'],
            primarySourcePath: 'Knowledge_Base/raglocationconflict/location conflict probe.md',
            answerMustContain: ['control module location', 'Rack A', 'Rack B'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'stable control module location',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context', 'conflict'],
            acceptedRagSufficiencyStatuses: ['borderline'],
            acceptedRagDegradationStates: ['conflict'],
            requiredRagFailureStages: ['context_assembly'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'temporal_scoped_state_status_probe_en',
        description: 'A scoped note with current and historical status facts should retain both facts without degrading as a conflict.',
        preloadTargets: ['ragtemporalqualifier'],
        activeTarget: 'ragtemporalqualifier',
        query: 'what is temporal state status probe?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['temporal state status probe'],
            primarySourcePath: 'Knowledge_Base/ragtemporalqualifier/temporal state status probe.md',
            answerMustContain: ['migration gate status', 'enabled', 'current'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'Conflicting evidence',
                'immediate predecessors',
                'likely next nodes',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context'],
            forbiddenRagRoles: ['conflict'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            acceptedRagDegradationStates: ['none'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'temporal_scoped_ownership_identity_probe_en',
        description: 'A scoped note with current and historical owner facts should retain both facts without degrading as a conflict.',
        preloadTargets: ['ragtemporalqualifier'],
        activeTarget: 'ragtemporalqualifier',
        query: 'what is temporal deployment owner probe?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['temporal deployment owner probe'],
            primarySourcePath: 'Knowledge_Base/ragtemporalqualifier/temporal deployment owner probe.md',
            answerMustContain: ['deployment owner', 'Release Ops', 'current'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'Conflicting evidence',
                'stable deployment owner',
                'immediate predecessors',
                'likely next nodes',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context'],
            forbiddenRagRoles: ['conflict'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            acceptedRagDegradationStates: ['none'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'environment_scoped_state_status_probe_en',
        description: 'A scoped note with staging and production status facts should retain both environment-qualified facts without degrading as a conflict.',
        preloadTargets: ['ragenvironmentqualifier'],
        activeTarget: 'ragenvironmentqualifier',
        query: 'what is environment scoped state status probe?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['environment scoped state status probe'],
            primarySourcePath: 'Knowledge_Base/ragenvironmentqualifier/environment scoped state status probe.md',
            answerMustContain: ['migration gate status', 'enabled', 'staging'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'Conflicting evidence',
                'stable migration gate status',
                'immediate predecessors',
                'likely next nodes',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context'],
            forbiddenRagRoles: ['conflict'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            acceptedRagDegradationStates: ['none'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'environment_scoped_ownership_identity_probe_en',
        description: 'A scoped note with staging and production owner facts should retain both environment-qualified identity facts without degrading as a conflict.',
        preloadTargets: ['ragenvironmentqualifier'],
        activeTarget: 'ragenvironmentqualifier',
        query: 'what is environment scoped deployment owner probe?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['environment scoped deployment owner probe'],
            primarySourcePath: 'Knowledge_Base/ragenvironmentqualifier/environment scoped deployment owner probe.md',
            answerMustContain: ['deployment owner', 'Release Ops', 'staging'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'Conflicting evidence',
                'stable deployment owner',
                'immediate predecessors',
                'likely next nodes',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context'],
            forbiddenRagRoles: ['conflict'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            acceptedRagDegradationStates: ['none'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'version_scoped_state_status_probe_en',
        description: 'A scoped note with version-specific status facts should retain both version-qualified facts without degrading as a conflict.',
        preloadTargets: ['ragversionqualifier'],
        activeTarget: 'ragversionqualifier',
        query: 'what is version scoped state status probe?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['version scoped state status probe'],
            primarySourcePath: 'Knowledge_Base/ragversionqualifier/version scoped state status probe.md',
            answerMustContain: ['migration gate status', 'enabled', 'version 1.0'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'Conflicting evidence',
                'stable migration gate status',
                'immediate predecessors',
                'likely next nodes',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context'],
            forbiddenRagRoles: ['conflict'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            acceptedRagDegradationStates: ['none'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'version_scoped_ownership_identity_probe_en',
        description: 'A scoped note with version-specific owner facts should retain both version-qualified identity facts without degrading as a conflict.',
        preloadTargets: ['ragversionqualifier'],
        activeTarget: 'ragversionqualifier',
        query: 'what is version scoped deployment owner probe?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['version scoped deployment owner probe'],
            primarySourcePath: 'Knowledge_Base/ragversionqualifier/version scoped deployment owner probe.md',
            answerMustContain: ['deployment owner', 'Release Ops', 'version 1.0'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'Conflicting evidence',
                'stable deployment owner',
                'immediate predecessors',
                'likely next nodes',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context'],
            forbiddenRagRoles: ['conflict'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            acceptedRagDegradationStates: ['none'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'platform_scoped_state_status_probe_en',
        description: 'A scoped note with OS/platform-specific status facts should retain both platform-qualified facts without degrading as a conflict.',
        preloadTargets: ['ragplatformqualifier'],
        activeTarget: 'ragplatformqualifier',
        query: 'what is platform scoped state status probe?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['platform scoped state status probe'],
            primarySourcePath: 'Knowledge_Base/ragplatformqualifier/platform scoped state status probe.md',
            answerMustContain: ['migration gate status', 'enabled', 'Windows'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'Conflicting evidence',
                'stable migration gate status',
                'immediate predecessors',
                'likely next nodes',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context'],
            forbiddenRagRoles: ['conflict'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            acceptedRagDegradationStates: ['none'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'platform_scoped_ownership_identity_probe_en',
        description: 'A scoped note with OS/platform-specific owner facts should retain both platform-qualified identity facts without degrading as a conflict.',
        preloadTargets: ['ragplatformqualifier'],
        activeTarget: 'ragplatformqualifier',
        query: 'what is platform scoped deployment owner probe?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['platform scoped deployment owner probe'],
            primarySourcePath: 'Knowledge_Base/ragplatformqualifier/platform scoped deployment owner probe.md',
            answerMustContain: ['deployment owner', 'Release Ops', 'Windows'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'Conflicting evidence',
                'stable deployment owner',
                'immediate predecessors',
                'likely next nodes',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context'],
            forbiddenRagRoles: ['conflict'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            acceptedRagDegradationStates: ['none'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'temporal_scoped_location_probe_en',
        description: 'A scoped note with current and historical location facts should retain both facts without degrading as a conflict.',
        preloadTargets: ['ragtemporalqualifier'],
        activeTarget: 'ragtemporalqualifier',
        query: 'what is temporal location probe?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['temporal location probe'],
            primarySourcePath: 'Knowledge_Base/ragtemporalqualifier/temporal location probe.md',
            answerMustContain: ['control module location', 'Rack A', 'current'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'Conflicting evidence',
                'immediate predecessors',
                'likely next nodes',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context'],
            forbiddenRagRoles: ['conflict'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            acceptedRagDegradationStates: ['none'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'temporal_scoped_release_date_probe_en',
        description: 'A scoped note with current and historical release dates should retain both facts without degrading as a conflict.',
        preloadTargets: ['ragtemporalqualifier'],
        activeTarget: 'ragtemporalqualifier',
        query: 'what is temporal release date probe?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['temporal release date probe'],
            primarySourcePath: 'Knowledge_Base/ragtemporalqualifier/temporal release date probe.md',
            answerMustContain: ['migration release date', '2026-08-15', 'current'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'Conflicting evidence',
                'immediate predecessors',
                'likely next nodes',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context'],
            forbiddenRagRoles: ['conflict'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            acceptedRagDegradationStates: ['none'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'temporal_scoped_planned_release_date_probe_en',
        description: 'A scoped note with current and planned release dates should retain both facts without degrading as a conflict.',
        preloadTargets: ['ragtemporalqualifier'],
        activeTarget: 'ragtemporalqualifier',
        query: 'what is temporal planned release date probe?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['temporal planned release date probe'],
            primarySourcePath: 'Knowledge_Base/ragtemporalqualifier/temporal planned release date probe.md',
            answerMustContain: ['migration release date', '2026-08-15', 'current'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'Conflicting evidence',
                'immediate predecessors',
                'likely next nodes',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context'],
            forbiddenRagRoles: ['conflict'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            acceptedRagDegradationStates: ['none'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'temporal_cross_document_planned_release_date_probe_en',
        description: 'Current and planned release dates in separate scoped documents should remain condition-qualified evidence instead of cross-document conflict.',
        preloadTargets: ['ragtemporalcrossscope'],
        activeTarget: 'ragtemporalcrossscope',
        query: 'compare temporal current release source with temporal planned roadmap source',
        expected: {
            minCitations: 2,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: [
                'temporal current release source',
                'temporal planned roadmap source',
            ],
            primarySourcePath: 'Knowledge_Base/ragtemporalcrossscope/temporal planned roadmap source.md',
            answerMustContain: ['migration release date', '2026-08-15', '2026-09-20', 'planned'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'Conflicting evidence',
                'immediate predecessors',
                'likely next nodes',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context'],
            forbiddenRagRoles: ['conflict'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            acceptedRagDegradationStates: ['none'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'conflicting_multi_document_evidence_probe_en',
        description: 'Two scoped documents with contradictory calibration tolerance facts should degrade as cross-document conflict.',
        preloadTargets: ['ragmulticonflict'],
        activeTarget: 'ragmulticonflict',
        query: 'compare multi document calibration tolerance conflict probe with field calibration tolerance conflict evidence',
        expected: {
            minCitations: 2,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: [
                'multi document calibration tolerance conflict probe',
                'field calibration tolerance conflict evidence',
            ],
            primarySourcePath: 'Knowledge_Base/ragmulticonflict/field calibration tolerance conflict evidence.md',
            answerMustContain: ['calibration tolerance', '+/-0.10 mm', '+/-0.50 mm'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'single stable calibration tolerance',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context', 'conflict'],
            acceptedRagSufficiencyStatuses: ['borderline'],
            acceptedRagDegradationStates: ['conflict'],
            requiredRagFailureStages: ['context_assembly'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'conflicting_multi_document_quantity_evidence_probe_en',
        description: 'Two scoped documents with contradictory plural unitless quantity facts should degrade as cross-document conflict.',
        preloadTargets: ['ragquantitymulticonflict'],
        activeTarget: 'ragquantitymulticonflict',
        query: 'compare nominal retry attempts quantity conflict probe with field retry attempts quantity conflict evidence',
        expected: {
            minCitations: 2,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: [
                'nominal retry attempts quantity conflict probe',
                'field retry attempts quantity conflict evidence',
            ],
            primarySourcePath: 'Knowledge_Base/ragquantitymulticonflict/field retry attempts quantity conflict evidence.md',
            answerMustContain: ['retry attempts', '3', '5'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'single stable retry-attempt count',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context', 'conflict'],
            acceptedRagSufficiencyStatuses: ['borderline'],
            acceptedRagDegradationStates: ['conflict'],
            requiredRagFailureStages: ['context_assembly'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'full_document_scan_remote_conflict_probe_en',
        description: 'Two scoped documents should be fully scanned for remote contradictions even when the matched spans are near the document starts.',
        preloadTargets: ['ragfullscan'],
        activeTarget: 'ragfullscan',
        query: 'compare nominal full scan source with field full scan source',
        expected: {
            minCitations: 2,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: [
                'nominal full scan source',
                'field full scan source',
            ],
            primarySourcePath: 'Knowledge_Base/ragfullscan/nominal full scan source.md',
            answerMustContain: ['calibration tolerance', '+/-0.10 mm', '+/-0.50 mm'],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'single stable calibration tolerance',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context', 'conflict'],
            acceptedRagSufficiencyStatuses: ['borderline'],
            acceptedRagDegradationStates: ['conflict'],
            requiredRagFailureStages: ['context_assembly'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'repeated_snippet_target_section_probe_en',
        description: 'A repeated snippet query should use the target section occurrence instead of leaking the distractor section context.',
        preloadTargets: ['ragrepeatedspan'],
        activeTarget: 'ragrepeatedspan',
        query: 'what is repeated snippet target section?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['repeated snippet target section'],
            primarySourcePath: 'Knowledge_Base/ragrepeatedspan/repeated snippet target section.md',
            answerMustContain: [
                'Target section context says the second occurrence controls the answer',
                'shared repeated wording',
            ],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'Distractor section context belongs to the first occurrence',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
        },
    },
    {
        id: 'contextbudget_source_window_truncation_en',
        description: 'A long scoped note should read the full source document while keeping the model-visible RAG pack budgeted.',
        preloadTargets: ['contextbudget'],
        activeTarget: 'contextbudget',
        query: 'what is context budget probe?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['context budget probe'],
            primarySourcePath: 'Knowledge_Base/contextbudget/context budget probe.md',
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            minimumRagSourceDecisionStatusCounts: {
                read: 1,
                fragment_truncated: 1,
            },
            requiredRagFailureStages: ['context_assembly'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            expectedRagRecoveryAttempted: false,
            acceptedRagDegradationStates: ['none'],
        },
    },
    {
        id: 'contextoverflow_no_provider_budget_drop_en',
        description: 'A dense scoped note should stay deterministic without an LLM provider and expose fragment-drop budget pressure.',
        preloadTargets: ['contextoverflow'],
        activeTarget: 'contextoverflow',
        query: 'what is overflow budget probe?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['overflow budget probe'],
            primarySourcePath: 'Knowledge_Base/contextoverflow/overflow budget probe.md',
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'llm_judge_failed',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            minimumRagSourceDecisionStatusCounts: {
                read: 1,
                fragment_dropped: 1,
            },
            requiredRagFailureStages: ['context_assembly'],
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            expectedRagRecoveryAttempted: false,
            inMemoryExpectedRagRecoveryAttempted: true,
            acceptedRagDegradationStates: ['none', 'partial_coverage'],
            inMemoryMinimumRagSourceDecisionStatusCounts: {
                read: 1,
            },
            inMemoryMinimumRagRecoveryBeforeSourceDecisionStatusCounts: {
                fragment_dropped: 1,
            },
        },
    },
    {
        id: 'contextoverflow_deep_profile_budget_en',
        description: 'An explicit deep scoped query should use the wider first-pass RAG answer profile without switching to an unbounded context pack.',
        preloadTargets: ['contextoverflow'],
        activeTarget: 'contextoverflow',
        query: 'explain in detail overflow budget probe',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['overflow budget probe'],
            primarySourcePath: 'Knowledge_Base/contextoverflow/overflow budget probe.md',
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'llm_judge_failed',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            expectedRagBudget: {
                maxFragments: 24,
                maxCharsPerFragment: 1600,
                maxTotalChars: 9000,
            },
            minimumRagSourceDecisionStatusCounts: {
                read: 1,
            },
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            expectedRagRecoveryAttempted: false,
            acceptedRagDegradationStates: ['none', 'partial_coverage'],
        },
    },
    {
        id: 'causal_answer_profile_budget_en',
        description: 'A causal why-query should use a wider bounded first-pass RAG answer profile without requiring an explicit deep prompt.',
        preloadTargets: ['ragcausalprofile'],
        activeTarget: 'ragcausalprofile',
        query: 'why causal answer profile probe needs bounded evidence?',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['why causal answer profile probe needs bounded evidence'],
            primarySourcePath: 'Knowledge_Base/ragcausalprofile/causal answer profile probe.md',
            answerMustContain: [
                'why question asks for mechanism evidence',
                'graph-neighbor evidence can clarify consequences',
            ],
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
                'llm_judge_failed',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            expectedRagBudget: {
                maxFragments: 20,
                maxCharsPerFragment: 1500,
                maxTotalChars: 7600,
            },
            minimumRagSourceDecisionStatusCounts: {
                read: 1,
            },
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            expectedRagRecoveryAttempted: false,
            acceptedRagDegradationStates: ['none', 'partial_coverage'],
            requirePlannerTitleHitDocumentIds: false,
            requireScopedDocumentIds: false,
        },
    },
    {
        id: 'contextoverflow_malformed_provider_judge_fallback_en',
        description: 'A dense scoped note should keep answering when a configured RAG sufficiency provider returns malformed judge JSON.',
        preloadTargets: ['contextoverflow'],
        activeTarget: 'contextoverflow',
        query: 'what is overflow budget probe?',
        topK: 12,
        runtimeProviderFixture: 'malformed_json',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['overflow budget probe'],
            primarySourcePath: 'Knowledge_Base/contextoverflow/overflow budget probe.md',
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            minimumRagSourceDecisionStatusCounts: {
                read: 1,
            },
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            expectedRagRecoveryAttempted: true,
            acceptedRagDegradationStates: ['none', 'partial_coverage'],
            minimumRagRecoveryBeforeSourceDecisionStatusCounts: {
                fragment_dropped: 1,
            },
            requiredRagFailureStages: ['context_assembly'],
            runtimeRequiredRagFailureStages: ['context_assembly', 'generation'],
            runtimeRequiredRagRecoveryBeforeReasonFragments: ['llm_judge_failed'],
        },
    },
    {
        id: 'contextoverflow_timeout_provider_judge_fallback_en',
        description: 'A dense scoped note should keep answering when a configured RAG sufficiency provider times out.',
        preloadTargets: ['contextoverflow'],
        activeTarget: 'contextoverflow',
        query: 'what is overflow budget probe?',
        topK: 12,
        runtimeProviderFixture: 'timeout',
        expected: {
            minCitations: 1,
            scopeSource: 'explicit_request',
            acceptedAnswerReleaseDecisions: ['release', 'revise'],
            plannerTitleLikeQueries: ['overflow budget probe'],
            primarySourcePath: 'Knowledge_Base/contextoverflow/overflow budget probe.md',
            answerMustNotContain: [
                'No scoped knowledge points matched',
                'retrieval_candidates_below_threshold',
            ],
            ragSourceBoundary: 'full_document',
            requiredRagRoles: ['direct_support', 'parent_context'],
            acceptedRagSufficiencyStatuses: ['sufficient', 'borderline'],
            minimumRagSourceDecisionStatusCounts: {
                read: 1,
            },
            expectedRagDeterministic: true,
            expectedRagLlmJudgeUsed: false,
            expectedRagRecoveryAttempted: true,
            acceptedRagDegradationStates: ['none', 'partial_coverage'],
            minimumRagRecoveryBeforeSourceDecisionStatusCounts: {
                fragment_dropped: 1,
            },
            requiredRagFailureStages: ['context_assembly'],
            runtimeRequiredRagFailureStages: ['context_assembly', 'generation'],
            runtimeRequiredRagRecoveryBeforeReasonFragments: ['llm_judge_failed'],
        },
    },
]);

export function selectKnowledgeWorkspaceConversationRegressionCases(
    caseIds?: readonly string[]
): KnowledgeWorkspaceConversationRegressionCase[] {
    if (!Array.isArray(caseIds) || caseIds.length <= 0) {
        return KNOWLEDGE_WORKSPACE_CONVERSATION_REGRESSION_CASES.slice();
    }
    const requestedIds = caseIds
        .map((caseId) => String(caseId || '').trim())
        .filter(Boolean);
    if (requestedIds.length <= 0) {
        return KNOWLEDGE_WORKSPACE_CONVERSATION_REGRESSION_CASES.slice();
    }
    const caseById = new Map(
        KNOWLEDGE_WORKSPACE_CONVERSATION_REGRESSION_CASES.map((entry) => [entry.id, entry] as const)
    );
    const selectedCases = requestedIds.map((caseId) => {
        const matchedCase = caseById.get(caseId);
        if (!matchedCase) {
            throw new Error(`Unknown knowledge workspace conversation regression case: ${caseId}`);
        }
        return matchedCase;
    });
    return selectedCases;
}
