import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
const { APPIMAGE_UPDATE_INFORMATION, verifyAppImageUpdate } = require('../scripts/appimage-update');

const describeLinux = process.platform === 'linux' ? describe : describe.skip;

describeLinux('AppImage update artifact boundary', () => {
  let directory: string;
  let artifact: string;
  const filename = 'NoteConnection_fixture_amd64.AppImage';
  const updateInformation = 'gh-releases-zsync|Jacobinwwey|NoteConnection|latest|NoteConnection_*_amd64.AppImage.zsync';
  const runtime = `#!/bin/sh\nprintf '%s\\n' '${updateInformation}'\n`;
  // Generated by bundled official zsyncmake 0.6.2: zsyncmake -u "$filename" "$filename".
  // The shell fixture exposes the runtime metadata boundary; its table is not synthesized by this test.
  const control = Buffer.from(
    'enN5bmM6IDAuNi4yCkZpbGVuYW1lOiBOb3RlQ29ubmVjdGlvbl9maXh0dXJlX2FtZDY0LkFwcEltYWdlCk1UaW1lOiBNb24sIDA1IE9jdCAyMDI2IDA0OjM4OjAwICswMDAwCkJsb2Nrc2l6ZTogMjA0OApMZW5ndGg6IDExNgpIYXNoLUxlbmd0aHM6IDEsMiw0ClVSTDogTm90ZUNvbm5lY3Rpb25fZml4dHVyZV9hbWQ2NC5BcHBJbWFnZQpTSEEtMTogYjY3NDMyZTc0ZDM1ZjI5MmNmOTA1ZWMzZDk2MGI5MDg5YjFkYjQwMQoK3tOgETED',
    'base64'
  );

  beforeEach(() => {
    directory = fs.mkdtempSync(path.join(os.tmpdir(), 'appimage update '));
    artifact = path.join(directory, filename);
    fs.writeFileSync(artifact, runtime, { mode: 0o755 });
    fs.writeFileSync(`${artifact}.zsync`, control);
  });

  afterEach(() => fs.rmSync(directory, { recursive: true, force: true }));

  test('accepts an official control file for the exact final bytes and Latest amd64 target', () => {
    expect(APPIMAGE_UPDATE_INFORMATION).toBe(updateInformation);
    expect(verifyAppImageUpdate(artifact)).toEqual({
      updateInformation,
      zsyncPath: `${artifact}.zsync`,
      sha1: 'b67432e74d35f292cf905ec3d960b9089b1db401',
    });
  });

  test('requires the companion file at the adjacent release path', () => {
    fs.renameSync(`${artifact}.zsync`, path.join(directory, 'elsewhere.zsync'));
    expect(() => verifyAppImageUpdate(artifact)).toThrow(/ENOENT/);
  });

  test.each(['', updateInformation.replace('Jacobinwwey', 'other-owner'),
    updateInformation.replace('|NoteConnection|', '|other-repository|'),
    updateInformation.replace('|latest|', '|v1.9.0|'),
    updateInformation.replace('_amd64.', '_aarch64.'),
    updateInformation.replace('_amd64.', '_*.'),
  ])('rejects missing or wrong embedded update target: %s', (metadata) => {
    fs.writeFileSync(artifact, `#!/bin/sh\nprintf '%s\\n' '${metadata}'\n`);
    expect(() => verifyAppImageUpdate(artifact)).toThrow(/update information must be/);
  });

  test.each(['Other_fixture_amd64.AppImage', 'NoteConnection_fixture_aarch64.AppImage'])(
    'rejects unsupported product or architecture: %s', (wrongName) => {
      const moved = path.join(directory, wrongName);
      fs.renameSync(artifact, moved);
      fs.renameSync(`${artifact}.zsync`, `${moved}.zsync`);
      expect(() => verifyAppImageUpdate(moved)).toThrow(/supported product amd64 filename/);
    }
  );

  test('rejects a stale control file after AppImage bytes are appended', () => {
    fs.appendFileSync(artifact, '# rebuilt\n');
    expect(() => verifyAppImageUpdate(artifact)).toThrow(/Length does not match/);
  });

  test('rejects same-size AppImage corruption even when metadata still prints correctly', () => {
    fs.writeFileSync(artifact, runtime.replace('printf ', 'printf\t'));
    expect(() => verifyAppImageUpdate(artifact)).toThrow(/SHA-1 does not match/);
  });

  test.each([
    ['Filename: NoteConnection_fixture_amd64.AppImage', 'Filename: old.AppImage', /Filename and relative URL/],
    ['URL: NoteConnection_fixture_amd64.AppImage', 'URL: https://example.com/image.AppImage', /Filename and relative URL/],
    ['Length: 116', 'Length: 117', /Length does not match/],
    ['Length: 116', 'Length: 1.16e2', /Length does not match/],
    ['Blocksize: 2048', 'Blocksize: 0', /Blocksize/],
    ['Blocksize: 2048', 'Blocksize: 2047', /Blocksize/],
    ['Blocksize: 2048', 'Blocksize: 9007199254740991', /Blocksize/],
    ['Hash-Lengths: 1,2,4', 'Hash-Lengths: 3,2,4', /Hash-Lengths/],
    ['Hash-Lengths: 1,2,4', 'Hash-Lengths: 1,5,4', /Hash-Lengths/],
    ['Hash-Lengths: 1,2,4', 'Hash-Lengths: 1,2,17', /Hash-Lengths/],
    ['Hash-Lengths: 1,2,4', 'Hash-Lengths: 1,2,3', /checksum table/],
    ['SHA-1: b67432e74d35f292cf905ec3d960b9089b1db401', 'SHA-1: 0000000000000000000000000000000000000000', /SHA-1 does not match/],
    ['zsync: 0.6.2', 'zsync: unknown', /format version/],
    ['MTime:', 'Min-Version:', /unsupported/],
    ['MTime:', 'Unknown:', /unsupported/],
    ['MTime:', 'Z-URL:', /unsupported/],
    ['MTime:', 'Filename:', /duplicate/],
    ['Filename: Note', 'Filename: \xceote', /malformed/],
  ])('rejects malformed or mismatched control field: %s', (before, after, message) => {
    fs.writeFileSync(`${artifact}.zsync`, Buffer.from(control.toString('latin1').replace(before as string, after as string), 'latin1'));
    expect(() => verifyAppImageUpdate(artifact)).toThrow(message as RegExp);
  });

  test('rejects a truncated checksum table', () => {
    fs.writeFileSync(`${artifact}.zsync`, control.subarray(0, -1));
    expect(() => verifyAppImageUpdate(artifact)).toThrow(/checksum table/);
  });

  test('rejects trailing bytes after the checksum table', () => {
    fs.appendFileSync(`${artifact}.zsync`, Buffer.from([0]));
    expect(() => verifyAppImageUpdate(artifact)).toThrow(/checksum table/);
  });

  test('rejects a header without the checksum table separator', () => {
    fs.writeFileSync(`${artifact}.zsync`, control.subarray(0, control.indexOf('\n\n')));
    expect(() => verifyAppImageUpdate(artifact)).toThrow(/separator/);
  });
});
